### ISSUE TITLE
移除台号登录过程中过多的信息框提示，以增加友好度

### ISSUE THREAD

**Issue by Tikas** [pungin/Beanfun#12]
## 现阶段台号登录过程：

登录 > 提示验证信息框 > 填写验证码 > 核对 ：错，继续提示；对，也继续提示 > 进入主界面

过多的提示信息框，会让用户经常过快按回车，导致当前激活的焦点放到登录界面，从而导致整个登录器崩溃

## 改进需求：

由于弹出验证码时，登录界面能看到，提示的信息框，反而会增加繁琐操作

验证码只要填写正确的，就不要去提示信息框了，直接进入主界面，以免由于弹出的信息框焦点异常，导致整个程序崩溃。

## 改进后流程：

登录  > 填写验证码 > 核对 ：错，继续提示；对，不提示 > 进入主界面

**Comment by pungin** [comment]
- [x] v3.1.0完成改动
