### ISSUE TITLE
無法開啟

### ISSUE THREAD

**Issue by zxa123854** [pungin/Beanfun#13]
我下載3.1.0版本解壓縮後打開後APP,開啟程式後跑出這樣的提示
![image](https://user-images.githubusercontent.com/71883630/94269203-eb75b000-ff70-11ea-8910-bad08412a116.png)
是我遺漏了什麼嗎? 
電腦版本 W7

**Comment by Tikas** [comment]
您需要安装更高版本的 .NET Framework 以解决这问题

[微软 .NET Framework 下载页面](https://dotnet.microsoft.com/download/dotnet-framework)

更多问题可以参考我的小站此文章：
[新枫之谷第三方缤放登录器使用教程-完全篇](https://xtikas.com/beanfun-stop-working.html)

**Comment by zxa123854** [comment]
已解決 感謝您
