### ISSUE TITLE
点击“启动游戏”时，增加 LE dll文件检测，以解决可能是 Locale Emulator 元件不支援您的系统问题。

### ISSUE THREAD

**Issue by Tikas** [pungin/Beanfun#14]
## 需要面临的困境

以 3.1 版本为例，缤放并不会自己释放 le 模块的 dll 文件。

如果用户的缤放目录内，没有此 LE dll 文件，将会让很多依赖缤放登录器来启动游戏的，无法正常进入游戏

### 1.主动检测

当用户点击 “启动游戏” 按钮事件时，优先增加检查缤放当前目录是否拥有 Le dll 文件，如果没有，释放一个

这方法优点是软件自己去解决，方便小白

缺点就是 beanfun.exe 会自己去创建 LocaleEmulator.dll 等相关文件，国内某些弱智推广流氓的安全软件，可能会进行风险提示。

### 2.发布新版本时，压缩包自带这些 dll 文件

这方法，如果是电脑小白，往往会只解压主程序出来。/哭

### 3.更新时检测所有 dll 依赖库

每当有新版本时，检查新的 dll 同时，也检查一下旧的 dll ，是否拥有

**Comment by pungin** [comment]
測試版已改回主動釋放LE相關檔案
