### ISSUE TITLE
Beanfun 有发布过 3.0.2 beta 版吗？

### ISSUE THREAD

**Issue by wyudong** [pungin/Beanfun#16]
Beanfun 有发布过 3.0.2 beta 版吗？在 Release 里没有找到，想确认下。

**Comment by pungin** [comment]
有的

**Comment by pungin** [comment]
有的



发自我的小米手机
在 Wang Yudong <notifications@github.com>，2020年10月4日 上午9:10写道：

Beanfun 有发布过 3.0.2 beta 版吗？在 Release 里没有找到，想确认下。
