### ISSUE TITLE
建议程序更新时覆盖原程序目录下旧文件，以方便更多人体验

### ISSUE THREAD

**Issue by Tikas** [pungin/Beanfun#18]
# 一、复盘升级事故

- [ ] 系统环境：windows 10
- [ ] 旧版本缤放登录器示例目录：D:\beanfun

1、运行旧版本缤放登录器，提示有新版本，点 “是” 进行在线更新
2、更新完毕重新启动缤放登录器（有两个，一个旧，一个新）

# 二、解读升级事故

1、查看新版本的缤放登录器所在目录，为：C:\Windows\SysWOW64
2、查看旧版本的缤放登录器所在目录，为：D:\beanfun

虽然缤放登录器已经有最新版本在电脑里存档，然而，由于我们桌面快捷方式一直是旧缤放的，所以会带来无限循环的提示有新版本

其事故步骤是这样的：

a、启动 D:\beanfun 目录下的旧版本缤放
b、提示有新版本，进行更新
c、更新完会重新启动两个缤放（一个旧，一个新），旧的还是在 D:\beanfun 目录下，新的在 C:\Windows\SysWOW64 目录里
d、下次再次启动桌面缤放登录器快捷方式 ，回到步骤 a
......
无限循环
......

# 三、解决升级事故

更新时，检测原来缤放所在目录，覆盖到原来目录即可

**Comment by pungin** [comment]
已取消自動更新功能 現在是直接開啟[發行版](https://github.com/pungin/Beanfun/releases)頁面
