### ISSUE TITLE
帳號登入失敗

### ISSUE THREAD

**Issue by ikarosu** [pungin/Beanfun#2]
今天點擊【啟動遊戲】之後，電腦自動重啟，重啟完，打開這個登錄程式，帳號密碼均為空白，手動輸入帳號密碼，提示密碼錯誤

**Comment by pungin** [comment]
帳號密碼空白可能是因為儲存的資料出錯了 為了防止無法啟動程式 會自動清除資料

然後後面的問題
1.在網頁是能登入的嗎
2.帳號區域與繽放的區域是相同的不

**Comment by ikarosu** [comment]
網頁也登不上，我想可能是我忘記了我的密碼，畢竟很久沒有手動輸入了。
希望告知我資料儲存的目錄，我想嘗試找回文件，否則我要經歷複雜的流程才能從beanfun找回我的密碼

**Comment by ikarosu** [comment]
希望增加機制來處理錯誤情況吧，防止資料丟失的此類事情
