### ISSUE TITLE
The underlying connection was closed:Could not establish trust relationship for she SLL/TLS secure channel

### ISSUE THREAD

**Issue by partrickHsu** [pungin/Beanfun#21]
更新最新版以后出现 从了都官网加载讯息出错，错误讯息：The underlying connection was closed:Could not establish trust relationship for she SLL/TLS secure channel。
不是加速器的问题，因为另一台电脑同一个加速器没有问题，更新到.net4.7.2以后也还是出现此错误，另一台电脑的登录器问还没更新，可以正常登录，现在找不到问题原因，不敢更新了
P.S：不止问一个人出现了这个问题，贴吧里看到有几个跟我相同遭遇的，盼复，谢谢

**Comment by pungin** [comment]
檢查一下Windows更新

**Comment by Toxuss** [comment]
我也遇見相同的問題了，Win7的就會出現這個，Win10的主機就沒有問題

**Comment by Prymon** [comment]
same problem
