### ISSUE TITLE
請問帳號資料有方法可以備份嗎?

### ISSUE THREAD

**Issue by dannypig79** [pungin/Beanfun#26]
想要重灌但是忘記分身的密碼...
目前也只剩這邊有辦法登入

**Comment by dannypig79** [comment]
原來有這種功能 謝謝!!

**Comment by alen84204** [comment]
酷 感覺很方便的東西
另外想問有沒有辦法知道帳號是甚麼
因為登入後 他不會自動帶入帳號密碼 我目前是QRCODE 所以帳號好像變成亂碼

**Comment by alen84204** [comment]
已解決 對帳號右鍵有很多功能可用
