### ISSUE TITLE
3.1.4版本無法自動輸入密碼

### ISSUE THREAD

**Issue by frank84610** [pungin/Beanfun#28]
3.1.4版本無法自動輸入密碼
勾選自動輸入的話會將密碼自動填到帳號的欄位
無法自動登入

**Comment by sorakunn** [comment]
+1

**Comment by flowerwOw0316** [comment]
一样

**Comment by pungin** [comment]
@sorakunn 
> +1

@flowerwOw0316 
> 一样

嘗試一下@frank84610 的改動 [Beanfun.zip](https://github.com/pungin/Beanfun/blob/bb2162eaf985b98d863e060339ce7db34f8ee525/Beanfun.zip)
