### ISSUE TITLE
已從伺服器斷線

### ISSUE THREAD

**Issue by Lin872** [pungin/Beanfun#29]
舊版本：3.0.1
新版本：3.1.4
使用舊版本長時間不動作，點擊獲取密碼不會出現[已從伺服器斷線，請重新登入]。
更新為新版本長時間不動作，點擊獲取密碼時常出現[已從伺服器斷線，請重新登入]。
![pic](https://user-images.githubusercontent.com/50880594/125258556-0ca56280-e331-11eb-96d7-7e42e67df7e3.JPG)

**Comment by pungin** [comment]
嘗試一下@frank84610 的修復 bb2162eaf985b98d863e060339ce7db34f8ee525 檔案 [Beanfun.zip](https://github.com/pungin/Beanfun/blob/bb2162eaf985b98d863e060339ce7db34f8ee525/Beanfun.zip)
