### ISSUE TITLE
WIN11无法启动游戏提示需要改成繁体

### ISSUE THREAD

**Issue by qq83826007** [pungin/Beanfun#30]
WIN11无法启动游戏提示需要改成繁体   希望可以解决下  辛苦了

This client can be executed only in Traditonsl Chinese code- page

**Comment by twjmy** [comment]
那應該只是楓之谷沒辦法啟動而已吧，`Win + R`打`intl.cpl`第二個標籤頁裡「非 Unicode 程式目前使用的的語言」改繁中了沒？
![image](https://user-images.githubusercontent.com/32490451/126269990-967cc6e2-647f-4af1-be83-bdcf9f3b9157.png)

**Comment by qq83826007** [comment]
我家裡電腦是WIN10&nbsp; 可以直接用登錄器啟動不需要把「非 Unicode 程式目前使用的的語言」設置成繁中 就可以啟動遊戲.
我單位電腦升級到了WIN11 應該是系統問題, 想啟動遊戲的話就必須改成繁中&nbsp; &nbsp;但是我單位的電腦沒辦法一直修改成繁中&nbsp; &nbsp;會影響工作的軟件.&nbsp; 所以想求助下有沒有別的解決方案




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pungin/Beanfun"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月20日(星期二) 下午2:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pungin/Beanfun] WIN11无法启动游戏提示需要改成繁体 (#30)





 
那應該只是楓之谷沒辦法啟動而已吧，Win + R打intl.cpl第二個標籤頁裡「非 Unicode 程式目前使用的的語言」改繁中了沒？

**Comment by pungin** [comment]
嘗試下這個版本[v3.1.6(1)](https://github.com/pungin/Beanfun/releases/tag/v3.1.6(1))

**Comment by qq83826007** [comment]
嘗試了下沒有問題   辛苦啦~

**Comment by wyudong** [comment]
[4.0.0](https://github.com/pungin/Beanfun/releases/tag/v4.0.0) 在 windows 10 上還會出現這個問題

![image](https://user-images.githubusercontent.com/5687273/134676957-94354c6f-c6b8-4f73-9ab0-90b14508257f.png)
