### ISSUE TITLE
運行beanfun后無反應

### ISSUE THREAD

**Issue by 18855441015** [pungin/Beanfun#31]
啓動程序后沒有響應怎麽辦

**Comment by pnzzud** [comment]
+1 游戏在登录界面就未响应

**Comment by pungin** [comment]
> 啓動程序后沒有響應怎麽辦

一般來說是網路延遲 啟動時會從頁面加載遊戲訊息 如果一段時間後還無法完成會彈出超時錯誤

> +1 游戏在登录界面就未响应

是遊戲未響應還是繽放 如果是遊戲的話那是遊戲本身的問題
