### ISSUE TITLE
登錄失敗，未找到samplecaptcha訊息

### ISSUE THREAD

**Issue by 582302894** [pungin/Beanfun#32]
登錄台灣beanfun帳號會這樣，登錄香港帳號沒有
![QQ截图20210804145231](https://user-images.githubusercontent.com/18064826/128135330-af3361e8-5e87-4bf4-aa0d-4c7c9b2844f9.png)

**Comment by secaaaaa** [comment]
這邊也是一樣。。。可能是軟件使用方法有誤吧
也有可能是橘子那邊出了點事情
希望這週之內還是能修好

**Comment by alen84204** [comment]
因V236改版，台灣帳號使用[帳號登入]會失效，建議先改用網頁帳號登入或是使用QRcord登入。

**Comment by pungin** [comment]
https://github.com/pungin/Beanfun/issues/33#issuecomment-916673492
