### ISSUE TITLE
關於新楓之谷V236登入失敗的問題

### ISSUE THREAD

**Issue by secaaaaa** [pungin/Beanfun#33]
這邊不太好上傳截圖，但是只有台號beanfun無法登入
顯示的訊息是  登入失敗，未找到Samplecaptcha訊息，請檢查網絡連接
這個問題是自橘子更新完楓谷之後出現的。。。。
（開其他遊戲也會彈一樣的訊息，目前不清楚是不是橘子那邊的問題，但想請開發者在近期內檢查下，或許是我用軟件的方式不對。。？）

**Comment by alen84204** [comment]
因V236改版，台灣帳號使用[帳號登入]會失效，建議先改用網頁帳號登入或是使用QRcord登入。

**Comment by secaaaaa** [comment]
> 
> 
> 因V236改版，台灣帳號使用[帳號登入]會失效，建議先改用網頁帳號登入或是使用QRcord登入。

那請問一下大概能在什麼時候修復這個問題
這邊還是想肝遊戲的
（還有改區用軟件好像衝突了。。？）

**Comment by pungin** [comment]
請更新到 [v3.1.5](https://github.com/pungin/Beanfun/releases/tag/v3.1.5) 以上
