### ISSUE TITLE
报错 mainformlmp:496 不点确定就会导致桌面就会卡住

### ISSUE THREAD

**Issue by f06521** [pungin/Beanfun#35]
請問报错 “mainformlmp:496 您的電腦異常，請先使用防毒程序檢查”
我扫描过系统并未发现病毒 然后要是不点确定，过会儿就会导致桌面就会卡住 请问这个有谁遇到过吗 怎么解决？谢谢 

![image](https://github.com/f06521/Test/blob/main/SNV%7D%7B%7D9Z19I8%7BVG3D%5DQM%5DE3.png?raw=true)

**Comment by pungin** [comment]
能提供一下你的系統版本 繽放版本 具體在哪個地方發生這個錯誤嗎
還有你這圖壞掉了

**Comment by f06521** [comment]
> 能提供一下你的系統版本 繽放版本 具體在哪個地方發生這個錯誤嗎
> 還有你這圖壞掉了
系统
Windows 10 专业版20H2 
19042.1165
事件查看器中的错误详情：
`应用程序: Beanfun.exe
Framework 版本: v4.0.30319
说明: 由于未经处理的异常，进程终止。
异常信息: System.NullReferenceException
   在 Beanfun.App.get_MainWnd()
   在 Beanfun.App.Application_Exit(System.Object, System.Windows.ExitEventArgs)
   在 System.Windows.Application.OnExit(System.Windows.ExitEventArgs)
   在 System.Windows.Application.DoShutdown()
   在 System.Windows.Application.ShutdownImpl()
   在 System.Windows.Application.ShutdownCallback(System.Object)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   在 System.Windows.Threading.DispatcherOperation.InvokeImpl()
   在 System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   在 MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   在 System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   在 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   在 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   在 MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   在 System.Windows.Threading.DispatcherOperation.Invoke()
   在 System.Windows.Threading.Dispatcher.ProcessQueue()
   在 System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   在 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   在 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   在 MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   在 System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   在 System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   在 System.Windows.Application.RunDispatcher(System.Object)
   在 System.Windows.Application.RunInternal(System.Windows.Window)
   在 System.Windows.Application.Run(System.Windows.Window)
   在 System.Windows.Application.Run()
   在 Beanfun.App.Main()
`
主要首此开启时就会出现 提示 如若不及时关闭就会导致资源管理器卡住

**Comment by pungin** [comment]
> 系统
> Windows 10 专业版20H2 19042.1165  
> beanfun 3.1.5
> 事件查看器中的错误详情：
> 
> `应用程序: Beanfun.exe 
> Framework 版本: v4.0.30319
> 说明: 由于未经处理的异常，进程终止。
> 异常信息: System.NullReferenceException
>    在 Beanfun.App.get_MainWnd()
>    在 Beanfun.App.Application_Exit(System.Object, System.Windows.ExitEventArgs)
>    在 System.Windows.Application.OnExit(System.Windows.ExitEventArgs)
>    在 System.Windows.Application.DoShutdown()
>    在 System.Windows.Application.ShutdownImpl()
>    在 System.Windows.Application.ShutdownCallback(System.Object)
>    在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
>    在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
>    在 System.Windows.Threading.DispatcherOperation.InvokeImpl()
>    在 System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
>    在 MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
>    在 System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
>    在 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
>    在 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
>    在 MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
>    在 System.Windows.Threading.DispatcherOperation.Invoke()
>    在 System.Windows.Threading.Dispatcher.ProcessQueue()
>    在 System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
>    在 MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
>    在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
>    在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
>    在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
>    在 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
>    在 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
>    在 MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
>    在 System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
>    在 System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
>    在 System.Windows.Application.RunDispatcher(System.Object)
>    在 System.Windows.Application.RunInternal(System.Windows.Window)
>    在 System.Windows.Application.Run(System.Windows.Window)
>    在 System.Windows.Application.Run()
>    在 Beanfun.App.Main()
> `
> 
> 主要首此开启时就会出现  后边不定时出现 提示若不及时点掉就会导致资源管理器卡住

你這個問題在這個版本應該解決了
https://github.com/pungin/Beanfun/releases/tag/v3.1.6%282%29

圖片那個問題不清楚，這好像不是繽放的報錯

**Comment by f06521** [comment]
好的 谢谢 

报错的 是这个~
- [Image] https://github.com/f06521/Test/blob/main/F%7DH%25PWSCRN_)I%7BA5)N%7D6)E2.png?raw=true
