### ISSUE TITLE
3.1.4.0版本可以正常使用，但是4.0.0.1版本無任何反應

### ISSUE THREAD

**Issue by LDH7755** [pungin/Beanfun#38]
如題，請問有遇到同樣情況的朋友嗎？

**Comment by ceezous** [comment]
无任何反应是指点击之后，光标转了一下圈圈就没有任何提示了吗？

**Comment by LDH7755** [comment]
> 无任何反应是指点击之后，光标转了一下圈圈就没有任何提示了吗？

是的是的！

**Comment by ceezous** [comment]
我把系统重装一次之后，按照网络上常见的步骤操作就好了；怀疑和某些配置文件有关。
