### ISSUE TITLE
下午更新了一下系统突然打不开了

### ISSUE THREAD

**Issue by flowerwOw0316** [pungin/Beanfun#40]
版本4.0最新那个版本
系统win10  21H1

**Comment by flowerwOw0316** [comment]
还发现在 文档目录里面的mybeanfun文件夹会导致软件闪退了

**Comment by leo-maybe** [comment]
厉害啊老哥，按你的办法解决了，谢谢。那看样子以后不能勾选自动登录了，我昨天把系统更新卸载，加速器换模式都没用。
