### ISSUE TITLE
关于 mainformlmp:496 报错

### ISSUE THREAD

**Issue by Yotsuba-Alice** [pungin/Beanfun#43]
作者您好！
我遇到了与某人相同的故障，“mainformlmp:496”
Beanfun 版本为 v3.1.6(2)
我自己尝试下来，SS开全局模式，直接启动Beanfun没有任何异常
但按平时使用方式，SS不启用系统代理，中间套用SocksCap64给Beanfun代理时，就会报错。

虽然这大概不是您软件本身的问题，但是想咨询一下，
依您的经验，是哪里存在的问题？或者有什么简单的解决方式？

**Comment by pungin** [comment]
沒有用SS進行代理 所以不清楚
