### ISSUE TITLE
将要更新64位客户端了，听闻LE不支持64位，会影响登录器使用吗

### ISSUE THREAD

**Issue by CielTerre** [pungin/Beanfun#46]
如题

**Comment by pungin** [comment]
会

**Comment by TestMsr** [comment]
![JY 2O7LTJZ6`X{5%OPF( 11](https://user-images.githubusercontent.com/10327983/154208793-e83a27ad-0107-427d-899e-7edce1ce2e89.png)

.Net是否有可以使用的ProcessStartInfo以指定用戶運行？ @pungin

**Comment by PSoul** [comment]
> ![JY 2O7LTJZ6`X{5%OPF( 11](https://user-images.githubusercontent.com/10327983/154208793-e83a27ad-0107-427d-899e-7edce1ce2e89.png)
> 
> .Net是否有可以使用的ProcessStartInfo以指定用戶運行？ @pungin

这个方法已经试过了，不行。系统的区域不区分用户，你换别的用户切区域所有用户都会切换。各位同学可以自行试试

**Comment by CielTerre** [comment]
看到大佬作者更新了64位兼容的，Releases 里的下载希望也能更新一下 @pungin
