### ISSUE TITLE
登陆器账户登入失败

### ISSUE THREAD

**Issue by zhengyi0414** [pungin/Beanfun#47]
在记住账密的情况下，出现“登入失败，账户或密码错误”的提示。
有时候重启可以解决，有时候不行。

已经大概解决了，新版本的软件名，必须和之前用的一样，否则就会密码错误，比如之前用的是beafun1.exe，那新版本下载后也必须命名为beafun1.exe

**Comment by pungin** [comment]
hk beanfun最近会检测IP，所以偶尔会提示出现IP异常的页面，这个页面就代表没登入成功，所以没获取到帐号
