### ISSUE TITLE
BFService有開放源碼的打算嗎？

### ISSUE THREAD

**Issue by dani3lWong** [pungin/Beanfun#49]
如題

**Comment by pungin** [comment]
BFService是官方的IE元件啊，如果你是說Interop.BFService.dll的話，這個是Visual Studio生成的

**Comment by dani3lWong** [comment]
> BFService是官方的IE元件啊，如果你是說Interop.BFService.dll的話，這個是Visual Studio生成的

好，我看看，沒怎麼碰C#的，謝謝
