### ISSUE TITLE
新版本在初始界面点击登陆后会停止工作

### ISSUE THREAD

**Issue by Yotsuba-Alice** [pungin/Beanfun#60]
新版本beanfun遇到一个麻烦，附上相关信息，能查看一下是什么原因引起的么？

问题签名:
  问题事件名称:	CLR20r3
  问题签名 01:	Beanfun.exe
  问题签名 02:	4.3.8089.23616
  问题签名 03:	6215c101
  问题签名 04:	mscorlib
  问题签名 05:	4.8.4480.0
  问题签名 06:	61d667c0
  问题签名 07:	db9
  问题签名 08:	11
  问题签名 09:	System.ArithmeticException
  OS 版本:	6.3.9600.2.0.0.256.48
  区域设置 ID:	2052
  其他信息 1:	5861
  其他信息 2:	5861822e1919d7c014bbb064c64908b2
  其他信息 3:	d1d9
  其他信息 4:	d1d94a13d3609d6b740644c12508f581

错误应用程序名称: Beanfun.exe，版本: 4.3.8089.23616，时间戳: 0x6215c101
错误模块名称: mscorlib.ni.dll，版本: 4.8.4480.0，时间戳: 0x61d667c0
异常代码: 0xc0000090
错误偏移量: 0x0042078a
错误进程 ID: 0x23a8
错误应用程序启动时间: 0x01d82876c8189e24
错误应用程序路径: E:\MXD\Beanfun 4.2\Beanfun.exe
错误模块路径: C:\Windows\assembly\NativeImages_v4.0.30319_32\mscorlib\f3b28b2a9beb297391f67f2e4386f26e\mscorlib.ni.dll
报告 ID: 0d633423-946a-11ec-8417-086266c74863
错误程序包全名: 
错误程序包相对应用程序 ID: 

应用程序: Beanfun.exe
Framework 版本: v4.0.30319
说明: 由于未经处理的异常，进程终止。
异常信息: System.ArithmeticException
   在 System.Double.Equals(System.Object)
   在 System.Object.Equals(System.Object, System.Object)
   在 System.Windows.DependencyObject.ProcessCoerceValue(System.Windows.DependencyProperty, System.Windows.PropertyMetadata, System.Windows.EntryIndex ByRef, Int32 ByRef, System.Windows.EffectiveValueEntry ByRef, System.Windows.EffectiveValueEntry ByRef, System.Object ByRef, System.Object, System.Object, System.Windows.CoerceValueCallback, Boolean, Boolean, Boolean)
   在 System.Windows.DependencyObject.UpdateEffectiveValue(System.Windows.EntryIndex, System.Windows.DependencyProperty, System.Windows.PropertyMetadata, System.Windows.EffectiveValueEntry, System.Windows.EffectiveValueEntry ByRef, Boolean, Boolean, System.Windows.OperationType)
   在 System.Windows.DependencyObject.CoerceValue(System.Windows.DependencyProperty)
   在 System.Windows.Controls.TextBlock.MeasureOverride(System.Windows.Size)
   在 System.Windows.FrameworkElement.MeasureCore(System.Windows.Size)
   在 System.Windows.UIElement.Measure(System.Windows.Size)
   在 MS.Internal.Helper.MeasureElementWithSingleChild(System.Windows.UIElement, System.Windows.Size)
   在 System.Windows.Controls.ContentPresenter.MeasureOverride(System.Windows.Size)
   在 System.Windows.FrameworkElement.MeasureCore(System.Windows.Size)
   在 System.Windows.UIElement.Measure(System.Windows.Size)
   在 System.Windows.Controls.Border.MeasureOverride(System.Windows.Size)
   在 System.Windows.FrameworkElement.MeasureCore(System.Windows.Size)
   在 System.Windows.UIElement.Measure(System.Windows.Size)
   在 System.Windows.Controls.Control.MeasureOverride(System.Windows.Size)
   在 System.Windows.FrameworkElement.MeasureCore(System.Windows.Size)
   在 System.Windows.UIElement.Measure(System.Windows.Size)
   在 System.Windows.Controls.StackPanel.StackMeasureHelper(System.Windows.Controls.IStackMeasure, System.Windows.Controls.IStackMeasureScrollData, System.Windows.Size)
   在 System.Windows.Controls.StackPanel.MeasureOverride(System.Windows.Size)
   在 System.Windows.FrameworkElement.MeasureCore(System.Windows.Size)
   在 System.Windows.UIElement.Measure(System.Windows.Size)
   在 System.Windows.Controls.StackPanel.StackMeasureHelper(System.Windows.Controls.IStackMeasure, System.Windows.Controls.IStackMeasureScrollData, System.Windows.Size)
   在 System.Windows.Controls.StackPanel.MeasureOverride(System.Windows.Size)
   在 System.Windows.FrameworkElement.MeasureCore(System.Windows.Size)
   在 System.Windows.UIElement.Measure(System.Windows.Size)
   在 System.Windows.Controls.DockPanel.MeasureOverride(System.Windows.Size)
   在 System.Windows.FrameworkElement.MeasureCore(System.Windows.Size)
   在 System.Windows.UIElement.Measure(System.Windows.Size)
   在 System.Windows.Controls.Grid.MeasureCell(Int32, Boolean)
   在 System.Windows.Controls.Grid.MeasureCellsGroup(Int32, System.Windows.Size, Boolean, Boolean, Boolean ByRef)
   在 System.Windows.Controls.Grid.MeasureOverride(System.Windows.Size)
   在 System.Windows.FrameworkElement.MeasureCore(System.Windows.Size)
   在 System.Windows.UIElement.Measure(System.Windows.Size)
   在 System.Windows.Controls.Grid.MeasureOverride(System.Windows.Size)
   在 System.Windows.FrameworkElement.MeasureCore(System.Windows.Size)
   在 System.Windows.UIElement.Measure(System.Windows.Size)
   在 MS.Internal.Helper.MeasureElementWithSingleChild(System.Windows.UIElement, System.Windows.Size)
   在 System.Windows.Controls.ContentPresenter.MeasureOverride(System.Windows.Size)
   在 System.Windows.FrameworkElement.MeasureCore(System.Windows.Size)
   在 System.Windows.UIElement.Measure(System.Windows.Size)
   在 System.Windows.Controls.Border.MeasureOverride(System.Windows.Size)
   在 System.Windows.FrameworkElement.MeasureCore(System.Windows.Size)
   在 System.Windows.UIElement.Measure(System.Windows.Size)
   在 System.Windows.Controls.Page.MeasureOverride(System.Windows.Size)
   在 System.Windows.FrameworkElement.MeasureCore(System.Windows.Size)
   在 System.Windows.UIElement.Measure(System.Windows.Size)
   在 MS.Internal.Helper.MeasureElementWithSingleChild(System.Windows.UIElement, System.Windows.Size)
   在 System.Windows.Controls.ContentPresenter.MeasureOverride(System.Windows.Size)
   在 System.Windows.FrameworkElement.MeasureCore(System.Windows.Size)
   在 System.Windows.UIElement.Measure(System.Windows.Size)
   在 System.Windows.ContextLayoutManager.UpdateLayout()
   在 System.Windows.ContextLayoutManager.UpdateLayoutCallback(System.Object)
   在 System.Windows.Media.MediaContext+InvokeOnRenderCallback.DoWork()
   在 System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   在 System.Windows.Media.MediaContext.RenderMessageHandlerCore(System.Object)
   在 System.Windows.Media.MediaContext.RenderMessageHandler(System.Object)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   在 System.Windows.Threading.DispatcherOperation.InvokeImpl()
   在 System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   在 MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   在 System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   在 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   在 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   在 MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   在 System.Windows.Threading.DispatcherOperation.Invoke()
   在 System.Windows.Threading.Dispatcher.ProcessQueue()
   在 System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   在 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   在 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   在 MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   在 System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   在 System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   在 System.Windows.Application.RunDispatcher(System.Object)
   在 System.Windows.Application.RunInternal(System.Windows.Window)
   在 System.Windows.Application.Run(System.Windows.Window)
   在 Beanfun.App.Main()

**Comment by Tikas** [comment]
您需要修复  .net 运行库，或者修复一下系统

**Comment by Tikas** [comment]
未安装合理的运行库也会导致此问题发生，您可以来这里安装一下所有 vc 运行库。

[前往 Github 下载所有的微软运行库](https://github.com/abbodi1406/vcredist/releases/latest)

**Comment by lancelotnemoj** [comment]
我發現可能是因爲win11推送了 2022-02 适用于 Windows 11 x64 的 .NET Framework 3.5 和 4.8 的累积更新预览 (KB5010474) 導致的。我這邊兩臺電腦都是安裝更新后無法運行，但是我沒有辦法卸載掉這個更新

**Comment by Tikas** [comment]
我的系统也是 windows 11 ，一直保持更新，并没有出现您这情况。

![image](https://user-images.githubusercontent.com/3396710/156887051-d862702e-8de7-42a9-8d0c-de114bffdb2c.png)

**Comment by Yotsuba-Alice** [comment]
抱歉中间工作太忙，没有来回复

后面我尝试用Locale_Remulator.1.4.1加载Beanfun.exe可以正常启动，
而且挂载Locale_Remulator与不挂在Locale_Remulator启动时，beanfun的界面UI会略有区别。

既然不太可能是简中系统引发的问题，但是能否请作者有空的时候查看一下挂载Locale_Remulator会使beanfun发生那些变化？

**Comment by Tikas** [comment]
LR 可能初始化了另一个默认的字体，这是我猜测的，您可以自行查看相送 LR 的源码

**Comment by injertao** [comment]
@Yotsuba-Alice 遇到相同的问题,请问你有解决吗?使用 Locale_Remulator 加载也不行

**Comment by Tikas** [comment]
@injertao 使用 LR 太新版本会导致 MS 无法正常使用，作者也说了，有的人会这样，暂时无法解决，请使用前一个测试版本

**Comment by injertao** [comment]
@Tikas 不是MS的问题哦,是Beanfun自身的问题, 不过4.3确实没问题

**Comment by Tikas** [comment]
要不，这个问题关闭了吧，今天给我带来了很大的困扰，如下图：

![%F(Q{4N8%9M8PX4U(V_20D8](https://github.com/pungin/Beanfun/assets/3396710/b0cb24e5-10fe-475e-8fed-381132559536)

点进来显示：

![DQS82$X@J$_LV E76 7 JUW](https://github.com/pungin/Beanfun/assets/3396710/7f93ff60-0b43-4c3b-9a61-fa92ef07d883)

这回复不都 2022 年吗，现在已经 2023 年了，我太难了，进来楞是看了半天
