### ISSUE TITLE
检测不到游戏正在运行。

### ISSUE THREAD

**Issue by mikuyourworld** [pungin/Beanfun#61]
明明游戏正在运行 但是点开启游戏 不会像以前弹出提示 游戏正在运行 是否中止。

**Comment by WeiWeic6222848** [comment]
手动更新检测也失效了，如果没有更新游戏就会闪退

**Comment by pungin** [comment]
嘗試更新到 [v4.4 Beta2](https://github.com/pungin/Beanfun/releases/tag/v4.4.2203081935)
