### ISSUE TITLE
自从更新V241，启动游戏提示 找不到指定的模块 LRHookx64.dll，而文件夹里面确实有这个文件

### ISSUE THREAD

**Issue by xiaoxiaosenlin** [pungin/Beanfun#64]

**Comment by Tikas** [comment]
解决此问题，请您更新微软的 VC 运行库即可

[更多问题解决方法请查阅](https://xtikas.com/pungin-beanfun.html)

**Comment by xiaoxiaosenlin** [comment]
> 

我已经更新了，安装了最新版的VC运行库了，提示我已经安装了，更高版本

**Comment by pungin** [comment]
https://github.com/pungin/Beanfun/issues/39#issuecomment-1050973620

**Comment by Tikas** [comment]
@xiaoxiaosenlin 目前由于运行库版本较多，我并没有花时间去测试具体需要那几个运行库，如果可以，请直接下载 all in one 的运行库进行更新，此问题我已经帮多人解决，并没有出现您所说的更新后还是不能使用。

**Comment by xiaoxiaosenlin** [comment]
> 
我已经找到解决方法了，安装 VC_redist.x64 就正常了

**Comment by Tikas** [comment]
@xiaoxiaosenlin 您好，为了规范一下 issues 区

请您把此问题的 `open` 状态改为 `closed`
