### ISSUE TITLE
Beanfun can't open it.

### ISSUE THREAD

**Issue by zio114905** [pungin/Beanfun#65]
Beanfun can't open it. It started several times, but it didn't respond.

Beanfun can't open it. It started several times, but it didn't respond.

**Comment by Tikas** [comment]
Can you provide relevant pictures or give more hints?

**Comment by zio114905** [comment]
启动beanfun之后在任务管理器会显示beanfun然后跳出来个werfault.exe应用程序错误beanfun就没了   之前删除machine.config    和   web.config后打开beanfun后 还原这两个文件beanfun就能打开了  然而关闭了下一次再开还要重复上面的操作

**Comment by zio114905** [comment]
系统环境去哪里找 我系统是win10的
beanfun: 4.4
.NET framework: 4.8提示我有这个版本或者更高版本的

**Comment by zio114905** [comment]
今天掉线之后就显示 释放区域模拟插件错误，请重新启动电脑后再次尝试 #
![image](https://user-images.githubusercontent.com/100258019/156628366-8852a8c3-a55e-4ba6-a625-09d0156df2a3.png)

**Comment by Tikas** [comment]
您好，可以方便进行远程您的电脑吗？

我一直想查看此问题的怎么发生的，然而朋友们没有这个现象，如果方便，您可以联系我 QQ：87182380

远程使用 todesk 进行，由于今天下午我需要出去，晚上方便。

**Comment by Tikas** [comment]
此问题是因为您第一次启动时，选中了 `自动登录`，下次再启动时就会出现这种情况。

请不要选中自动登录！！！

解决办法：

* 1、打开运行窗口（按 `Win` + `R` 键）
* 2、在运行窗口里输入：**`%APPDATA%`**（注：复制时请包括前后两个 % 号）
* 3、在弹出的资源管理器里找到 `Beanfun` 目录，如：AppData\Roaming\Beanfun
* 4、删除里面的 `Config.xml` 文件（注：别一个是存放账号信息，删了就没账号记录了，只有此文件才是缤放登录器的配置文件）
* 5、再次启动，请别再选中自动登录！
