### ISSUE TITLE
我这边一直打不开显示“出现了一个问题，导致程序停止正常工作。请关闭该程序。”

### ISSUE THREAD

**Issue by jeffersfay** [pungin/Beanfun#68]
我这边一直打不开显示“出现了一个问题，导致程序停止正常工作。请关闭该程序。
![QQ截图20220225233706](https://user-images.githubusercontent.com/100429152/155743510-16798a48-68bd-4b46-a73c-9754a88b4d9a.png)
”

**Comment by pungin** [comment]
https://github.com/pungin/Beanfun/issues/39#issuecomment-1050973620

**Comment by jeffersfay** [comment]
> [#39 (comment)](https://github.com/pungin/Beanfun/issues/39#issuecomment-1050973620)

您好！我根据
![QQ截图20220225233706](https://user-images.githubusercontent.com/100429152/155770939-20ca3188-9dec-40c3-affb-f7fcc75d13e6.png)
你的安装步骤，安装了.NET Framework 4.8 和 Microsoft Visual C++ Redistributable重启后依然报错。

**Comment by Tikas** [comment]
@jeffersfay 看您的操作系统是 Windows 7，请您下载 4.6.2 版本的 .NET 运行库

您可以从此链接下载：[微软官方下载地址](https://dotnet.microsoft.com/en-us/download/dotnet-framework/net462)

Download .NET framework 4.6.2 runtime 就是

因为 4.8 对 windows 7 支持并不好，依旧容易出现停止工作，已经测试 win 7 支持最好的就是 4.6.2

**Comment by Tikas** [comment]
您好，为保持 Issues 区良好氛围，请把此问题的 open 状态改为 closed
