### ISSUE TITLE
關於遊戲中文鍵入問題

### ISSUE THREAD

**Issue by LTColittle** [pungin/Beanfun#69]
**使用輸入法後會出現亂碼選項*，無法正常鍵入文字。
![q211](https://user-images.githubusercontent.com/100504481/155869461-7c992d4d-edca-4dbb-b21d-22932ac63f6b.png)

**Comment by pungin** [comment]
試下更新到 [v4.4 Beta1](https://github.com/pungin/Beanfun/releases/tag/v4.4.2202272141)

**Comment by LTColittle** [comment]
問題解決。 XD  3Q~  另外一直不懂下載文檔中的GZ 和 ZIP  文檔的區別

**Comment by LTColittle** [comment]
登入器最近版本都無法直接在軟體的檢測更新上更新。

**Comment by pungin** [comment]
> 問題解決。 XD 3Q~ 另外一直不懂下載文檔中的GZ 和 ZIP 文檔的區別

建議翻譯一下他們前面的Source code是什麼意思

**Comment by pungin** [comment]
> 登入器最近版本都無法直接在軟體的檢測更新上更新。

Pre-release 版本只有設置更新通道為「測試版」才會收到
