### ISSUE TITLE
出现异常情况

### ISSUE THREAD

**Issue by a7891749** [pungin/Beanfun#7]
无法加载进行反序列化所需的类型Beanfun. Records。
在System.Runtime.Serialization.ObjectManager. DoFixups0
在
System.Runtime.Serialization.Formatters. Binary.ObjectReader.Deserialize(HeaderH
andler handler, BinaryParser serParser, Boolean fCheck, Boolean
isCrossAppDomain, IMethodCallMessage methodCallMessage)
System.Runtime.Serialization.Formatters. Binary.BinaryFormatter.Deserialize(Stream
serializationStream, HeaderHandler handler, Boolean fCheck, Boolean
isCrossAppDomain, IMethodCallMessage methodCallMessage)
在Beanfun.AccountManager.c0
在Beanfun.AccountManager.initO
在Beanfun.MainWindow.ctor0

**Comment by pungin** [comment]
看[這裡](https://github.com/pungin/Beanfun/releases/tag/v3.0.1)第一行加粗的文字
