### ISSUE TITLE
點擊啟動遊戲, 提示找不到LRHook32.dll

### ISSUE THREAD

**Issue by LemondCloud** [pungin/Beanfun#72]
![image](https://user-images.githubusercontent.com/100771199/156352957-e1e05f00-6dc7-4ed8-8e31-e4c7ae71c782.png)
使用的v4.3
3月2日使用MapleStory_241.2fix更新前後都是一樣的提示,嘗試換最新測試版登錄器也一樣.

**Comment by lilifan1598** [comment]
我也出现了一样的提示

**Comment by LemondCloud** [comment]
已经确定是我更新文件解压错地方了, 新版本似乎也没正确提示版本没跟新, 所以还是留着吧

**Comment by Tikas** [comment]
此问题是由于登录器禁止更新导致的，由于游戏检测到有新版本时，会启用更新程序，此程序依旧是 32 位应用程序，故，需要加载 LRHook32.dll 模块来启动，由于默认运行游戏时是加载 LRHook64.dll ，此时容易出现一些问题

解决办法：

* 1、增加版本检测，并提示。
* 2、检测到 play 窗口之后进行更新，登录器改用 LRHook32.dll 去运行更新程序

**Comment by Tikas** [comment]
其实 32 位可以继续使用旧的 LE 模块，这或许是更稳定的办法。

**Comment by pungin** [comment]
嘗試更新到 [v4.4 Beta2](https://github.com/pungin/Beanfun/releases/tag/v4.4.2203081935)

**Comment by mapllllle** [comment]
> 尝试更新到[v4.4 Beta2](https://github.com/pungin/Beanfun/releases/tag/v4.4.2203081935)

您好，我使用了4.4版登陆器后没有报LRhook的错误了，但是登陆器还是卡死了。这是任务管理器的截图和错误日志，希望您可以帮助我解决问题
![@YK{AYMXSV33W${4$O S(}O](https://user-images.githubusercontent.com/101327541/158565912-4ce7a99b-9438-40ac-94ed-4b18276ff77d.png)
![9O1I`CKOSSRF)G7~BIPUOS3](https://user-images.githubusercontent.com/101327541/158567719-dc2ac4bc-3e3f-4ac0-a069-d8b8f5ce35e7.png)
![KCL@G5K2NZ O@{8BANWSF1C](https://user-images.githubusercontent.com/101327541/158568051-32c52681-5795-4027-89a2-70fdc1064cc5.png)

**Comment by Tikas** [comment]
您好，看事件，这是 C# 运行库内部处理的问题，看您的系统是 win 10，如果可以，请尝试更新一下系统，看看能不能更新运行库的相关补丁。

C# 虽然很方便，但是不同的版本各自有着不同的特性，这完全是一个大坑，非常容易发生许多让人无法预料的问题。

当然，也可能是程序的逻辑没优化好，由于我对 C# 并不了解，只能猜测可能是而已。
