### ISSUE TITLE
4.4释放区域模拟插件错误

### ISSUE THREAD

**Issue by leo-maybe** [pungin/Beanfun#73]
使用4.4启动游戏会弹出“释放区域模拟插件错误，请重新启动电脑后再次尝试。”，但是重启无效，问题1：能进游戏，但过一会儿会自动关闭; 问题2：在选择人物进入游戏界面卡很久，然后自动关闭游戏。使用4.3没问题。

**Comment by Tikas** [comment]
您好，不知道可否方便远程您的电脑，以方便我来对此问题进行跟进

**Comment by dai-key** [comment]
4.4出现这个问题后，换4.3只会跳过play后完全没有其他反应

**Comment by Tikas** [comment]
> 4.4出现这个问题后，换4.3只会跳过play后完全没有其他反应

最近游戏出了新的小版本更新档，不知您可有对游戏进行更新呢？

跳过 play 之后没反应，也许是新枫之谷游戏检测到本地游戏并不是最新版本，而执行了更新程序。

由于新版本缤放并没有对此事件进行一个合理的判断处理，可能由此导致之后的完全没有其他反应。

**Comment by dai-key** [comment]
> 
确实是没有更新版本造成的

**Comment by Tikas** [comment]
此问题是因为您第一次启动时，选中了 `自动登录`，下次再启动时就会出现这种情况。

请不要选中自动登录！！！

解决办法：

* 1、打开运行窗口（按 `Win` + `R` 键）
* 2、在运行窗口里输入：**`%APPDATA%`**（注：复制时请包括前后两个 % 号）
* 3、在弹出的资源管理器里找到 `Beanfun` 目录，如：AppData\Roaming\Beanfun
* 4、删除里面的 `Config.xml` 文件（注：别一个是存放账号信息，删了就没账号记录了，只有此文件才是缤放登录器的配置文件）
* 5、再次启动，请别再选中自动登录！

**Comment by leo-maybe** [comment]
> 此问题是因为您第一次启动时，选中了 `自动登录`，下次再启动时就会出现这种情况。
> 
> 请不要选中自动登录！！！
> 
> 解决办法：
> 
> * 1、打开运行窗口（按 `Win` + `R` 键）
> * 2、在运行窗口里输入：**`%APPDATA%`**（注：复制时请包括前后两个 % 号）
> * 3、在弹出的资源管理器里找到 `Beanfun` 目录，如：AppData\Roaming\Beanfun
> * 4、删除里面的 `Config.xml` 文件（注：别一个是存放账号信息，删了就没账号记录了，只有此文件才是缤放登录器的配置文件）
> * 5、再次启动，请别再选中自动登录！

**Comment by leo-maybe** [comment]
按照你说的操作删除里面的 Config.xml 文件，还是会提示释放区域模拟插件错误，有空的话，我可以远端给你操作一下，或者我演示给你看。

**Comment by Tikas** [comment]
可以的，您可以加我 QQ：87182380，使用 todesk 远程，多数晚上 10 点之后才有时间

**Comment by Tikas** [comment]
@pungin 远程之后，并没能有效发现是什么原因导致此问题发生。也许需要对源码分析，进行相关事件处理

**Comment by Tikas** [comment]
依旧会提示，但是不影响正常游戏

**Comment by pungin** [comment]
嘗試更新到 [v4.4 Beta2](https://github.com/pungin/Beanfun/releases/tag/v4.4.2203081935)

**Comment by leo-maybe** [comment]
> 嘗試更新到 [v4.4 Beta2](https://github.com/pungin/Beanfun/releases/tag/v4.4.2203081935)

感谢，幸苦了
