### ISSUE TITLE
beanfun登录后启动游戏时，beanfun自动退出，然后windows通知栏弹出beanfun网页已关闭

### ISSUE THREAD

**Issue by tyaathome** [pungin/Beanfun#74]
beanfun登录后启动游戏时，beanfun自动退出，然后windows通知栏弹出beanfun网页已关闭
如图
![91c12c002baa735d660da7a73b27a2b](https://user-images.githubusercontent.com/6203047/156930895-ef52875a-bb73-422d-99da-0deae3f02f67.png)

**Comment by JJlll3005** [comment]
遇到了一样的问题

**Comment by faitian995** [comment]
不知道你们的问题解决了吗？怎么解决的？
