### ISSUE TITLE
功能建议：跟进港号新增同台号一样的登录方式

### ISSUE THREAD

**Issue by Tikas** [pungin/Beanfun#85]
最近有很多新人告诉我，他们查看的香港官网和我所描述的不是一样，可以无需安装 beanfun 外挂程序，进行游戏。

新的页面：https://bfweb.hk.beanfun.com/

希望能增加此登录接口

谢谢！

**Comment by mapledot** [comment]
> 最近有很多新人告诉我，他们查看的香港官网和我所描述的不是一样，可以无需安装 beanfun 外挂程序，进行游戏。
> 
> 新的页面：https://bfweb.hk.beanfun.com/
> 
> 希望能增加此登录接口
> 
> 谢谢！

实际上没区别，就是废弃了IE插件，换成chrome，firefox，edge插件了
