### ISSUE TITLE
網路無斷線密碼獲取失敗

### ISSUE THREAD

**Issue by peter5417** [pungin/Beanfun#9]
今天開始
突然想換遊戲帳號登入就密碼獲取失敗
以為是半夜換IP造成無法獲取密碼
但上午時遊戲無任何斷線
只是想換遊戲帳號登入卻不能獲取密碼
繽放可以電腦不關機的話一直正常使用
沒想到今天突然出了問題
好難過

**Comment by pungin** [comment]
大概是網絡不太好(自己這邊或者橘子那邊)
